### ISSUE TITLE
Compile error in xmlParser -- template parameter shadowing

### ISSUE THREAD

**Issue by flyingfalling** [jahuth/virtualretina#10]
I found and fixed a compile issue with the included xmlParser library.

In the file 
External_Libraries/xmlParameters++-1.1.1/src/xmlobject_container_specialisation.h

The inner Cont class parameters need to be changed to different names than the template class names.

In other words, all instances need to be changed to this, otherwise compilers will complain that the template parameters are shadowed and error out (at least with modern GCC):
Fixing all lines to this fixes the issue.

template<typename XMLIZED, typename ALLOC, template <typename XMLIZED2, typename ALLOC2> class Cont>

**Comment by jahuth** [comment]
That's great!
I'll do a test build and approve your pull request.
