### ISSUE TITLE
mvaspike no longer available

### ISSUE THREAD

**Issue by CollinsEM** [jahuth/virtualretina#13]
The build process cannot complete due to the failure to retrieve the mvaspike package. I've searched briefly online, and I cannot find any repository for the mvaspike package that still has a functioning link. The [main project site](https://gforge.inria.fr/projects/mvaspike) appears to no longer be available.

> Installing MVASPIKE (spiking network library) locally
> 
> ----------------------------------------
> --2022-10-23 06:47:25--  http://gforge.inria.fr/frs/download.php/file/32318/mvaspike-1.0.18.tar.gz
> Resolving gforge.inria.fr (gforge.inria.fr)... 128.93.162.203
> Connecting to gforge.inria.fr (gforge.inria.fr)|128.93.162.203|:80... connected.
> HTTP request sent, awaiting response... 301 Moved Permanently
> Location: https://gforge.inria.fr/frs/download.php/file/32318/mvaspike-1.0.18.tar.gz [following]
> --2022-10-23 06:47:26--  https://gforge.inria.fr/frs/download.php/file/32318/mvaspike-1.0.18.tar.gz
> Connecting to gforge.inria.fr (gforge.inria.fr)|128.93.162.203|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2022-10-23 06:47:26 ERROR 403: Forbidden.
> 
> tar (child): mvaspike-1.0.18.tar.gz: Cannot open: No such file or directory
> tar (child): Error is not recoverable: exiting now
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now
> rm: cannot remove 'mvaspike-1.0.18.tar.gz': No such file or directory
> Entering External_Libraries/mvaspike-1.0.18
> download_build_all.bash: line 127: cd: mvaspike-1.0.18: No such file or directory
> download_build_all.bash: line 128: ./configure: No such file or directory
> make: *** No targets specified and no makefile found.  Stop.
> make: *** No rule to make target 'install'.  Stop.
>

**Comment by AdrienWohrer** [comment]
Probably a little late, but I have now included mvaspike in the VirtualRetina repository, so it is functional again. For the moment this change is only available in my own fork of VirtualRetina:
https://github.com/AdrienWohrer/virtualretina
I also made a pull request here, so hopefully this repository will soon also have a fixed version a well.

**Comment by jahuth** [comment]
Hi all!

I just accepted the pull request #14 , so the external mvaspike library is now part of the repository.
